# Generated by Django 6.1.1 on 2026-09-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_estimated_wait_minutes_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
