# Generated by Django 6.1.1 on 2026-09-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seed_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=20),
        ),
    ]
